"""Initial tables with workout types

Revision ID: 7169d5a548c4
Revises: 
Create Date: 2025-05-16 12:50:53.007237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7169d5a548c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('distance', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=20), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('sets',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sets',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('duration')
        batch_op.drop_column('distance')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
