"""Adding user preferences

Revision ID: 8c5b263b610e
Revises: 6c65e3111c3e
Create Date: 2025-05-16 17:14:07.294011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5b263b610e'
down_revision = '6c65e3111c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units', sa.String(length=10), nullable=False, server_default='metric'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('units')

    # ### end Alembic commands ###
